In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset =pd.read_csv("cervical-cancer1.csv")
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,-1].values

In [10]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Assuming 'x' is a pandas DataFrame
df = pd.DataFrame(x)  # Convert 'x' to DataFrame if it's not already

# Replace 'NaN' string or any other placeholder with actual NaN values
df = df.replace('NaN', pd.NA)

# Create SimpleImputer with 'mean' strategy
imputer = SimpleImputer(strategy='mean')

# Apply imputer to the DataFrame
df_imputed = imputer.fit_transform(df)  # This applies to all columns by default

# Convert back to DataFrame if needed (optional)
df_imputed = pd.DataFrame(df_imputed, columns=df.columns)


In [12]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# Assuming 'x' is a pandas DataFrame and 'y' is the target variable
df = pd.DataFrame(x)  # Convert 'x' to DataFrame if it's not already

# Replace 'NaN' string or any other placeholder with actual NaN values
df = df.replace('NaN', pd.NA)

# Create SimpleImputer with 'mean' strategy
imputer = SimpleImputer(strategy='mean')

# Apply imputer to the DataFrame
df_imputed = imputer.fit_transform(df)  # This applies to all columns by default

# Convert back to DataFrame with original column names
df_imputed = pd.DataFrame(df_imputed, columns=df.columns)

# Now, split the imputed data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(df_imputed, y, test_size=0.30, random_state=0)


In [13]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [16]:
#Get the correlation of the columns
dataset.corr()


Age  Number of sexual partners  \
Age                                 1.000000                   0.255091   
Number of sexual partners           0.255091                   1.000000   
First sexual intercourse            0.109288                   0.011980   
Num of pregnancies                  0.435311                   0.019803   
Smokes                              0.201569                   0.276692   
Smokes (years)                      0.385804                   0.297935   
Smokes (packs/year)                 0.313058                   0.342667   
Hormonal Contraceptives             0.099211                   0.099978   
Hormonal Contraceptives (years)     0.147031                   0.011744   
IUD                                 0.109747                  -0.041100   
IUD (years)                         0.084017                  -0.165236   
STDs                                0.033552                  -0.101611   
STDs (number)                       0.053786                  -0.152711   
STDs:condylomatosis                 0.071472                  -0.193022   
STDs:cervical condylomatosis             NaN                        NaN   
STDs:vaginal condylomatosis              NaN                        NaN   
STDs:vulvo-perineal condylomatosis  0.071472                  -0.193022   
STDs:syphilis                       0.007797                   0.087556   
STDs:pelvic inflammatory disease         NaN                        NaN   
STDs:genital herpes                      NaN                        NaN   
STDs:molluscum contagiosum               NaN                        NaN   
STDs:AIDS                                NaN                        NaN   
STDs:HIV                           -0.039098                  -0.069585   
STDs:Hepatitis B                         NaN                        NaN   
STDs:HPV                                 NaN                        NaN   
STDs: Number of diagnosis           0.022791                  -0.123234   
STDs: Time since first diagnosis    0.032974                   0.978117   
STDs: Time since last diagnosis     0.032974                   0.978117   
Dx:Cancer                           0.272416                  -0.046007   
Dx:CIN                             -0.039098                  -0.069585   
Dx:HPV                              0.272416                  -0.046007   
Dx                                  0.071472                  -0.193022   
Hinselmann                          0.214741                  -0.099496   
Schiller                            0.100597                  -0.180543   
Citology                            0.027732                  -0.200406   
Biopsy                              0.116796                  -0.162838   

                                    First sexual intercourse  \
Age                                                 0.109288   
Number of sexual partners                           0.011980   
First sexual intercourse                            1.000000   
Num of pregnancies                                 -0.290411   
Smokes                                             -0.111310   
Smokes (years)                                     -0.139872   
Smokes (packs/year)                                -0.146326   
Hormonal Contraceptives                            -0.061613   
Hormonal Contraceptives (years)                    -0.065540   
IUD                                                -0.013535   
IUD (years)                                        -0.141656   
STDs                                               -0.089717   
STDs (number)                                      -0.057311   
STDs:condylomatosis                                 0.006379   
STDs:cervical condylomatosis                             NaN   
STDs:vaginal condylomatosis                              NaN   
STDs:vulvo-perineal condylomatosis                  0.006379   
STDs:syphilis                                      -0.116100   
STDs:pelvic inflammatory disease                 

In [30]:
def models(x_train,y_train):
  
  #Using Logistic Regression Algorithm to the Training Set
  from sklearn.linear_model import LogisticRegression
  log = LogisticRegression(random_state = 12345)
  log.fit(x_train, y_train)

  #Using KNeighborsClassifier Method of neighbors class to use Nearest Neighbor algorithm
  from sklearn.neighbors import KNeighborsClassifier
  knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
  knn.fit(x_train, y_train)

  #Using SVC method of svm class to use Support Vector Machine Algorithm
  from sklearn.svm import SVC
  svc_lin = SVC(kernel = 'linear', random_state = 0)
  svc_lin.fit(x_train, y_train)

  #Using SVC method of svm class to use Kernel SVM Algorithm
  from sklearn.svm import SVC
  svc_rbf = SVC(kernel = 'rbf', random_state = 0)
  svc_rbf.fit(x_train, y_train)

  #Using GaussianNB method of naïve_bayes class to use Naïve Bayes Algorithm
  from sklearn.naive_bayes import GaussianNB
  gauss = GaussianNB()
  gauss.fit(x_train, y_train)

  #Using DecisionTreeClassifier of tree class to use Decision Tree Algorithm
  from sklearn.tree import DecisionTreeClassifier
  tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
  tree.fit(x_train, y_train)

  #Using RandomForestClassifier method of ensemble class to use Random Forest Classification algorithm
  from sklearn.ensemble import RandomForestClassifier
  forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
  forest.fit(x_train, y_train)
  
  #print model accuracy on the training data.
  print('[0]Logistic Regression Training Accuracy:', log.score(x_train, y_train))
  print('[1]K Nearest Neighbor Training Accuracy:', knn.score(x_train, y_train))
  print('[2]Support Vector Machine (Linear Classifier) Training Accuracy:', svc_lin.score(x_train, y_train))
  print('[3]Support Vector Machine (RBF Classifier) Training Accuracy:', svc_rbf.score(x_train, y_train))
  print('[4]Gaussian Naive Bayes Training Accuracy:', gauss.score(x_train, y_train))
  print('[5]Decision Tree Classifier Training Accuracy:', tree.score(x_train, y_train))
  print('[6]Random Forest Classifier Training Accuracy:', forest.score(x_train, y_train))
  
  return log, knn, svc_lin, svc_rbf, gauss, tree, forest

In [31]:
model = models(x_train,y_train)

[0]Logistic Regression Training Accuracy: 1.0
[1]K Nearest Neighbor Training Accuracy: 0.8529411764705882
[2]Support Vector Machine (Linear Classifier) Training Accuracy: 1.0
[3]Support Vector Machine (RBF Classifier) Training Accuracy: 0.9705882352941176
[4]Gaussian Naive Bayes Training Accuracy: 1.0
[5]Decision Tree Classifier Training Accuracy: 1.0
[6]Random Forest Classifier Training Accuracy: 0.9705882352941176


In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Assuming 'model' is a list of trained models
for i in range(len(model)):
    # Predict the labels on the test data using the current model
    y_pred = model[i].predict(x_test)

    # Calculate the confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Calculate the accuracy of the model
    accuracy = accuracy_score(y_test, y_pred)

    # Print confusion matrix and accuracy for the model
    print(f"Model {i+1} - Confusion Matrix:")
    print(cm)
    print(f"Model {i+1} - Accuracy: {accuracy:.2f}\n")


Model 1 - Confusion Matrix:
[[15]]
Model 1 - Accuracy: 1.00

Model 2 - Confusion Matrix:
[[15]]
Model 2 - Accuracy: 1.00

Model 3 - Confusion Matrix:
[[14  1]
 [ 0  0]]
Model 3 - Accuracy: 0.93

Model 4 - Confusion Matrix:
[[15]]
Model 4 - Accuracy: 1.00

Model 5 - Confusion Matrix:
[[14  1]
 [ 0  0]]
Model 5 - Accuracy: 0.93

Model 6 - Confusion Matrix:
[[14  1]
 [ 0  0]]
Model 6 - Accuracy: 0.93

Model 7 - Confusion Matrix:
[[15]]
Model 7 - Accuracy: 1.00



In [28]:
#Print Prediction of Random Forest Classifier model
pred = model[2].predict(x_test)
print(pred)
#Print a space
print()
#Print the actual values
print(y_test)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
